### PR TITLE
fix fail to dail to xds istiod.istio-system.svc:15012

### PR DESCRIPTION
**Pull request by shencurl521**
issue ：https://github.com/aeraki-mesh/aeraki/issues/389

### CODE REVIEW

**Comment by zhaohuabing** [comment]
@shencurl521 Could you please sign the commits in this PR？

https://github.com/aeraki-mesh/aeraki/pull/402/checks?check_run_id=19555129630

**Comment by shencurl521** [comment]
> @shencurl521 Could you please sign the commits in this PR？
> 
> https://github.com/aeraki-mesh/aeraki/pull/402/checks?check_run_id=19555129630

sorry format incorrect

**Comment by zhaohuabing** [comment]
Pleas fix the go lint issue.

**Comment by shencurl521** [comment]
> Please fix the go lint issue.
fixed

**Review by zhaohuabing — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
